import pandas as pd
import numpy as np
from typing import List, Tuple, Union, Optional
from loguru import logger
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import KFold, StratifiedKFold
from lightgbm import early_stopping, log_evaluation
import matplotlib.pyplot as plt
import seaborn as sns
import gc
from scipy.stats import yeojohnson


# ==================================================================================================================== #
#                                                  DATA TRANSFORMATION                                                 #
# ==================================================================================================================== #
def one_hot_encoder(dataframe: pd.DataFrame, nan_as_category: bool = True) -> Tuple[pd.DataFrame, List[str]]:
    """
    One-hot encodes categorical columns in a DataFrame, including NaN values as a separate category if specified.

    Args:
        dataframe (pd.DataFrame): The input DataFrame containing categorical and non-categorical columns.
        nan_as_category (bool, optional): Whether to treat NaN values in categorical columns as a separate category.
                                          Defaults to True.

    Returns:
        Tuple[pd.DataFrame, List[str]]:
            - The transformed DataFrame with one-hot encoded columns.
            - A list of new columns generated by the one-hot encoding.

    Raises:
        ValueError: If the input DataFrame is empty or has no categorical columns.
    """
    if dataframe.empty:
        logger.error("The input DataFrame is empty.")
        raise ValueError("The input DataFrame must not be empty.")

    # Identify categorical columns
    categorical_columns = dataframe.select_dtypes(include=['object']).columns.tolist()
    if not categorical_columns:
        logger.warning("No categorical columns found in the DataFrame. Returning the original DataFrame.")
        return dataframe, []

    logger.debug(f"Identified {len(categorical_columns)} categorical columns for encoding.")

    # Perform one-hot encoding
    try:
        df_encoded = pd.get_dummies(dataframe, columns=categorical_columns, dummy_na=nan_as_category)
    except Exception as e:
        logger.exception("Failed during one-hot encoding.")
        raise ValueError(f"An error occurred during one-hot encoding: {e}")

    # Identify new columns generated by the encoding
    new_columns = [col for col in df_encoded.columns if col not in dataframe.columns]
    logger.success(f"Generated {len(new_columns)} new columns from one-hot encoding.")

    return df_encoded, new_columns


# ==================================================================================================================== #
#                                                MODELING AND EVALUATION                                               #
# ==================================================================================================================== #
def kfold_lightgbm(df: pd.DataFrame, num_folds: int, stratified: bool = False) -> pd.DataFrame:
    """
    Runs a LightGBM model with K-Fold or Stratified K-Fold cross-validation using GPU acceleration.

    Args:
        df (pd.DataFrame): The input dataframe containing training and test data.
        num_folds (int): Number of folds for cross-validation.
        stratified (bool, optional): Whether to use stratified K-Fold. Defaults to False.

    Returns:
        pd.DataFrame: Dataframe containing feature importances across all folds.
    """
    import gc
    import numpy as np
    import pandas as pd
    from lightgbm import LGBMClassifier, early_stopping, log_evaluation
    from sklearn.model_selection import KFold, StratifiedKFold
    from sklearn.metrics import roc_auc_score

    # Split data into training and test sets based on the 'TARGET' column
    train_df = df[df['TARGET'].notnull()]
    test_df = df[df['TARGET'].isnull()].copy()
    logger.info(f"Starting LightGBM with KFold. Train shape: {train_df.shape}, Test shape: {test_df.shape}")
    del df
    gc.collect()  # Perform garbage collection

    # Initialize KFold or StratifiedKFold based on the 'stratified' parameter
    folds = StratifiedKFold(n_splits=num_folds, shuffle=True, random_state=42) if stratified else KFold(n_splits=num_folds, shuffle=True, random_state=42)
    logger.info(f"Using {'StratifiedKFold' if stratified else 'KFold'} with {num_folds} folds.")

    # Initialize arrays for out-of-fold predictions and test predictions
    oof_preds = np.zeros(train_df.shape[0])
    sub_preds = np.zeros(test_df.shape[0])
    feature_importance_df = pd.DataFrame()

    # Identify features to use for training
    feats = [f for f in train_df.columns if f not in ['TARGET', 'SK_ID_CURR', 'SK_ID_BUREAU', 'SK_ID_PREV', 'index']]

    # Iterate through each fold
    for n_fold, (train_idx, valid_idx) in enumerate(folds.split(train_df[feats], train_df['TARGET'])):
        logger.info(f"Starting fold {n_fold + 1}...")

        # Split the data into training and validation sets for the current fold
        train_x, train_y = train_df[feats].iloc[train_idx], train_df['TARGET'].iloc[train_idx]
        valid_x, valid_y = train_df[feats].iloc[valid_idx], train_df['TARGET'].iloc[valid_idx]

        # Initialize the LightGBM classifier with specified hyperparameters
        clf = LGBMClassifier(
            nthread=4,
            n_estimators=10000,
            learning_rate=0.02,
            num_leaves=34,
            colsample_bytree=0.9497036,
            subsample=0.8715623,
            max_depth=8,
            reg_alpha=0.041545473,
            reg_lambda=0.0735294,
            min_split_gain=0.0222415,
            min_child_weight=39.3259775,
            verbose=-1,
            random_state=42,
            device='gpu',  # Enable GPU
            gpu_platform_id=0,  # Specify GPU platform ID
            gpu_device_id=0  # Specify GPU device ID
            )

        # Train the model with early stopping and evaluation metrics
        clf.fit(
            train_x, train_y,
            eval_set=[(train_x, train_y), (valid_x, valid_y)],
            eval_metric='auc',
            callbacks=[early_stopping(200), log_evaluation(200)]
            )

        # Make predictions for validation and test sets
        oof_preds[valid_idx] = clf.predict_proba(valid_x, num_iteration=clf.best_iteration_)[:, 1]
        sub_preds += clf.predict_proba(test_df[feats], num_iteration=clf.best_iteration_)[:, 1] / folds.n_splits

        # Store feature importance for the current fold
        fold_importance_df = pd.DataFrame()
        fold_importance_df["feature"] = feats
        fold_importance_df["importance"] = clf.feature_importances_
        fold_importance_df["fold"] = n_fold + 1
        feature_importance_df = pd.concat([feature_importance_df, fold_importance_df], axis=0)

        # Calculate and log AUC score for the current fold
        auc_score = roc_auc_score(valid_y, oof_preds[valid_idx])
        logger.info(f'Fold {n_fold + 1} AUC : {auc_score:.6f}')

        # Clean up memory for the current fold
        del clf, train_x, train_y, valid_x, valid_y
        gc.collect()

    # Calculate and log the overall AUC score
    full_auc = roc_auc_score(train_df["TARGET"], oof_preds)
    logger.info(f'Full AUC score: {full_auc:.6f}')

    # Display feature importance across all folds
    display_importances(feature_importance_df)

    return feature_importance_df

def display_importances(feature_importance_df_: pd.DataFrame, top_n: int = 40) -> None:
    """
    Displays and saves a plot of feature importances.

    Args:
        feature_importance_df_ (pd.DataFrame): Dataframe containing feature importances.
        top_n (int, optional): Number of top features to display. Defaults to 40.
    """
    # Log the start of the visualization process
    logger.info(f"Displaying top {top_n} feature importances...")

    # Compute the average importance of each feature and select the top_n features
    cols = (
        feature_importance_df_[["feature", "importance"]]
        .groupby("feature")
        .mean()
        .sort_values(by="importance", ascending=False)
        .head(top_n)
        .index
    )

    # Filter the dataframe to include only the top features
    best_features = feature_importance_df_.loc[feature_importance_df_["feature"].isin(cols)]

    # Create the plot
    plt.figure(figsize=(8, 10))  # Set figure size
    sns.barplot(
        x="importance",
        y="feature",
        data=best_features.sort_values(by="importance", ascending=False),
        palette="viridis"
        )
    plt.title('LightGBM Features (avg over folds)', fontsize=14, weight='bold')  # Add a descriptive title
    plt.xlabel('Importance', fontsize=12)  # Label x-axis
    plt.ylabel('Feature', fontsize=12)  # Label y-axis
    plt.tight_layout()  # Adjust layout to avoid overlapping

    # Display the plot
    plt.show()

# ==================================================================================================================== #
#                                                  FILLING NAN VALUES                                                  #
# ==================================================================================================================== #
import faiss
import numpy as np
import pandas as pd
from loguru import logger
from sklearn.preprocessing import RobustScaler
import warnings
from typing import List

warnings.filterwarnings("ignore", category=SyntaxWarning)

def faiss_knn_imputation(
        df: pd.DataFrame,
        target_column: str = "TARGET",
        bool_column: str = "CODE_GENDER_0",
        threshold: float = 25.0,
        valid_row_threshold: float = 0.5,  # Adjusted to 50% for more valid rows
        batch_size: int = 40000
        ) -> pd.DataFrame:
    """
    FAISS-based Hybrid KNN Imputation:
        - Non-Iterative for columns ≤ threshold missing values.
        - Iterative for columns > threshold missing values.
        - Valid rows: rows with > valid_row_threshold non-NaN values.
        - Remaining NaNs after FAISS are filled with the column median.
    """
    try:
        logger.info(f"Starting FAISS KNN imputation for dataframe with shape: {df.shape}")
        df = df.copy()

        # Store original data types
        original_dtypes = df.dtypes

        # Replace infinite values with NaN
        df.replace([np.inf, -np.inf], np.nan, inplace=True)

        # Exclude target column and split into column groups
        complete_cols: List[str] = df.columns[df.isna().sum() == 0].tolist()
        target_excluded = [col for col in df.columns if col != target_column]
        features: List[str] = [col for col in target_excluded if col not in complete_cols]
        missing_percentage = df[features].isna().mean().sort_values()

        non_iterative_cols = missing_percentage[missing_percentage <= threshold / 100].index.tolist()
        iterative_cols = missing_percentage[missing_percentage > threshold / 100].index.tolist()

        logger.info(f"Fully filled columns: {complete_cols}")
        logger.info(f"Non-Iterative Columns (<= {threshold}% missing): {non_iterative_cols}")
        logger.info(f"Iterative Columns (> {threshold}% missing): {iterative_cols}")

        # Prepare RobustScaler for numeric columns except the bool column
        scaler = RobustScaler()
        scale_cols = [col for col in features if col != bool_column]
        df_scaled = df.copy()
        df_scaled[scale_cols] = scaler.fit_transform(df[scale_cols])

        # Define FAISS Imputation Function
        def faiss_impute(current_col: str, df_scaled: pd.DataFrame, iterative: bool = False):
            """Impute missing values for the specified column using FAISS KNN."""
            other_cols = [c for c in scale_cols if c != current_col]

            # Valid rows threshold
            valid_rows = df_scaled[other_cols].notna().sum(axis=1) >= len(other_cols) * valid_row_threshold
            valid_rows &= df_scaled[current_col].notna()
            valid_data = df_scaled.loc[valid_rows, other_cols].to_numpy().astype(np.float32)

            if len(valid_data) == 0:
                logger.warning(f"No valid rows available for column '{current_col}'. Skipping...")
                return

            row_norms = np.linalg.norm(valid_data, axis=1, keepdims=True)
            normalized_data = valid_data / np.maximum(row_norms, 1e-8)

            # Build FAISS Index
            index = faiss.IndexFlatIP(normalized_data.shape[1])
            index.add(normalized_data)

            rows_with_nan = df_scaled[other_cols].notna().sum(axis=1) >= len(other_cols) * valid_row_threshold
            rows_with_nan &= df_scaled[current_col].isna()
            rows_to_impute = df_scaled.loc[rows_with_nan, other_cols].to_numpy().astype(np.float32)

            if len(rows_to_impute) == 0:
                logger.warning(f"No rows to impute for column '{current_col}'.")
                return

            row_norms = np.linalg.norm(rows_to_impute, axis=1, keepdims=True)
            normalized_rows = rows_to_impute / np.maximum(row_norms, 1e-8)

            imputed_values = []
            for start_idx in range(0, normalized_rows.shape[0], batch_size):
                batch = normalized_rows[start_idx:start_idx + batch_size]
                _, neighbors = index.search(batch, 50)  # Increase k to 50
                for neighbor_idx in neighbors:
                    neighbor_values = valid_data[neighbor_idx][:, 0]
                    valid_neighbors = neighbor_values[~np.isnan(neighbor_values)]
                    if len(valid_neighbors) == 0:  # Check if there are no valid neighbors
                        logger.warning(f"No valid neighbors found for batch in column '{current_col}'")
                        imputed_values.append(np.nan)
                    else:
                        imputed_values.append(np.median(valid_neighbors))

            df_scaled.loc[rows_with_nan, current_col] = imputed_values

        # Non-Iterative Imputation
        for i, col in enumerate(non_iterative_cols):
            logger.info(f"Non-Iterative FAISS --> {i+1}/{len(non_iterative_cols)} | {col}")
            faiss_impute(col, df_scaled, iterative=False)

        # Iterative Imputation
        for i, col in enumerate(iterative_cols):
            logger.info(f"Iterative FAISS --> {i+1}/{len(iterative_cols)} | {col}")
            faiss_impute(col, df_scaled, iterative=True)

        # Reverse scaling
        df[scale_cols] = scaler.inverse_transform(df_scaled[scale_cols])

        # Check for remaining NaN values and fill with median
        remaining_nans = df[features].isna().sum()
        remaining_cols = remaining_nans[remaining_nans > 0].index.tolist()

        if remaining_cols:
            logger.warning("The following columns still contain NaN values after FAISS imputation:")
            for col in remaining_cols:
                percent_missing = (remaining_nans[col] / len(df)) * 100
                logger.warning(f" - Column '{col}': {percent_missing:.5f}% missing ({remaining_nans[col]} rows)")
                # Fill with median
                df[col].fillna(df[col].median(), inplace=True)
                logger.info(f"Filled column '{col}' with its median value.")

        # Reapply original data types
        for col in features:
            df[col] = df[col].astype(original_dtypes[col])

        logger.info("FAISS KNN imputation complete.")
        return df[[target_column] + [col for col in df.columns if col != target_column]]

    except Exception as e:
        logger.exception(f"Error during FAISS KNN imputation: {e}")
        raise













