[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[theme]
base = "light"

[global]
dataFrameSerialization = "legacy"
disableWatchdogWarning = true

[runner]
magicEnabled = false

[session]
idle_timeout = 300
